name: segment-brain-mri
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - pip
  - pip:
    - eikonalfm==0.9.5
    - matplotlib==3.3.3
    - pandas==1.1.5
    - plotly==4.14.1
    - scikit-image==0.18.0
    - scikit-learn==0.24.0
    - torch==1.7.1
    - torchaudio==0.7.2
    - torchvision==0.8.2
    - tqdm==4.55.0
